# rabbitmq conf file

# memory management
vm_memory_high_watermark.relative = 0.6

# disk space management
disk_free_limit.absolute = 2GB

# SSL/TLS conf
ssl_options.verify = verify_none

# management plugin
management.tcp.port = 15672     # the prot of rabbitmq

# logging
log.file.level = info
log.console = true
log.console.level = info